"""add forwarded_emails

Revision ID: f5d614d8fceb
Revises: 2c284d7b10f3
Create Date: 2026-07-10 14:45:15.583346+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import src.db.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5d614d8fceb'
down_revision: str | None = '2c284d7b10f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forwarded_emails',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=320), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('data', src.db.types.MessageDetailsType(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forwarded_emails_client_id'), 'forwarded_emails', ['client_id'], unique=False)
    op.create_index(op.f('ix_forwarded_emails_message_id'), 'forwarded_emails', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forwarded_emails_message_id'), table_name='forwarded_emails')
    op.drop_index(op.f('ix_forwarded_emails_client_id'), table_name='forwarded_emails')
    op.drop_table('forwarded_emails')
    # ### end Alembic commands ###
