"""initial src schema

Revision ID: 2c284d7b10f3
Revises: 
Create Date: 2026-07-10 12:30:11.524919+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c284d7b10f3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('inbox', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_inbox'), 'clients', ['inbox'], unique=True)
    op.create_index(op.f('ix_clients_inbox_id'), 'clients', ['inbox_id'], unique=True)
    op.create_index(op.f('ix_clients_telegram_id'), 'clients', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_telegram_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_inbox_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_inbox'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
